"""add model_version to drift_reports

Revision ID: 97b6edc32a02
Revises: 003
Create Date: 2026-04-18 04:13:55.980397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '97b6edc32a02'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_routing_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('drift_reports', sa.Column('model_version', sa.String(length=160), nullable=True))
    op.alter_column('drift_reports', 'check_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_reports', 'triggered_retraining',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_drift_time'), table_name='drift_reports')
    op.alter_column('pairwise_comparisons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pairwise_created'), table_name='pairwise_comparisons')
    op.drop_index(op.f('idx_pairwise_hash'), table_name='pairwise_comparisons')
    op.create_index(op.f('ix_pairwise_comparisons_text_hash'), 'pairwise_comparisons', ['text_hash'], unique=False)
    op.alter_column('prediction_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_predictions_created'), table_name='prediction_logs')
    op.drop_index(op.f('idx_predictions_hash'), table_name='prediction_logs')
    op.drop_index(op.f('idx_predictions_label'), table_name='prediction_logs')
    op.create_index(op.f('ix_prediction_logs_text_hash'), 'prediction_logs', ['text_hash'], unique=False)
    op.alter_column('training_runs', 'deployed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('training_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_training_status'), table_name='training_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_training_status'), 'training_runs', ['status'], unique=False)
    op.alter_column('training_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_runs', 'deployed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_prediction_logs_text_hash'), table_name='prediction_logs')
    op.create_index(op.f('idx_predictions_label'), 'prediction_logs', ['predicted_label'], unique=False)
    op.create_index(op.f('idx_predictions_hash'), 'prediction_logs', ['text_hash'], unique=False)
    op.create_index(op.f('idx_predictions_created'), 'prediction_logs', ['created_at'], unique=False)
    op.alter_column('prediction_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pairwise_comparisons_text_hash'), table_name='pairwise_comparisons')
    op.create_index(op.f('idx_pairwise_hash'), 'pairwise_comparisons', ['text_hash'], unique=False)
    op.create_index(op.f('idx_pairwise_created'), 'pairwise_comparisons', ['created_at'], unique=False)
    op.alter_column('pairwise_comparisons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_drift_time'), 'drift_reports', ['check_time'], unique=False)
    op.alter_column('drift_reports', 'triggered_retraining',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('drift_reports', 'check_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('drift_reports', 'model_version')
    op.alter_column('ab_routing_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
